#!/bin/bash

system() {
    LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"
    EWW_BIN="$HOME/.local/bin/eww"

    run() {
        sleep 0.2;
        ${EWW_BIN} -c $HOME/.config/eww/simple_one open system 
    }

    if [[ ! -f "$LOCK_FILE_MEM" ]]; then
        touch "$LOCK_FILE_MEM"
        run && echo "ok good!"
    else
        sleep 0.2;
        ${EWW_BIN} -c $HOME/.config/eww/simple_one close system 
        rm "$LOCK_FILE_MEM" && echo "closed"
    fi
}

if [ "$1" = "system" ]; then
system
fi