#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

#|    __  ___          _ __          
#|   /  |/  /__  ___  (_) /____  ____
#|  / /|_/ / _ \/ _ \/ / __/ _ \/ __/
#| /_/  /_/\___/_//_/_/\__/\___/_/   

bspc monitor HDMI2 -d 2 3 4 5
bspc monitor eDP1  -d 1

#|                 ____     
#|  _______  ___  / _(_)__ _
#| / __/ _ \/ _ \/ _/ / _ `/
#| \__/\___/_//_/_//_/\_, / 
#|                   /___/  

bspc config window_gap 7

bspc config focused_border_color  "#282828"
bspc config normal_border_color   "#101010"
bspc config active_border_color   "#101010"

bspc config presel_feedback_color "#CF9D71"
bspc config split_ratio 0.52

bspc config focus_follows_pointer true

#|    ___           
#|   / _ \__ _____  
#|  / , _/ // / _ \ 
#| /_/|_|\_,_/_//_/

nm-applet &

#| Auto run

bash ~/.config/bspwm/autorun/run.sh

bspc config border_width 2 

#|    ___       __       
#|   / _ \__ __/ /__ ___ 
#|  / , _/ // / / -_|_-< 
#| /_/|_|\_,_/_/\__/___/ 

bspc rule -a firefox          follow=off  focus=off
bspc rule -a discord          follow=off  focus=off
bspc rule -a Code             follow=off  focus=off
bspc rule -a Gpick            follow=off  state=floating
bspc rule -a Salwyrr Launcher follow=off  state=floating
bspc rule -a gimp             follow=off            
bspc rule -a Toolkit          follow=off  state=floating

