#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

#    __  ___          _ __          
#   /  |/  /__  ___  (_) /____  ____
#  / /|_/ / _ \/ _ \/ / __/ _ \/ __/
# /_/  /_/\___/_//_/_/\__/\___/_/   
#

bspc monitor HDMI-A-0 -d 1 2 3 4 5

#                 ____     
#  _______  ___  / _(_)__ _
# / __/ _ \/ _ \/ _/ / _ `/
# \__/\___/_//_/_//_/\_, / 
#                   /___/  

bspc config window_gap 15
bspc config border_width 0

bspc config focused_border_color  "#1c1c1c"
bspc config normal_border_color   "#161616"
bspc config active_border_color   "#161616"

bspc config presel_feedback_color "#1c1c1c"
bspc config focus_follows_pointer true
bspc config split_ratio 0.52

bspc rule -a "Lxappearance"   state=floating
bspc rule -a "gpick"          state=floating

bspc rule -a "*:Toolkit:Picture-in-Picture" state=floating sticky=on

#    ___           
#   / _ \__ _____  
#  / , _/ // / _ \ 
# /_/|_|\_,_/_//_/

bash ~/.config/bspwm/autorun/run.sh

