#!/bin/sh

symbol() {
[ $(cat /sys/class/net/enp*/operstate) = down ] && echo "󰅤" && exit
echo ""
}

class() {
[ $(cat /sys/class/net/enp*/operstate) = down ] && echo "wifi-down" && exit
echo "wifi-up"
}

name() {
nmcli | grep "^enp" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

[ "$1" = "icon" ]  && symbol && exit
[ "$1" = "name" ]  && name   && exit
[ "$1" = "class" ] && class  && exit
