#!/bin/sh

symbol() {
[ $(xset q | grep 'LED mask' | sed 's/.*\([0-9]\)$/\1/') = 1 ] && echo "󰬶" && exit
echo ""
}

class() {
[ $(xset q | grep 'LED mask' | sed 's/.*\([0-9]\)$/\1/') = 1 ] && echo "caps-on" && exit
echo "alert-off"
}

[ "$1" = "icon" ]  && symbol && exit
[ "$1" = "class" ] && class  && exit