#!/bin/sh

path=".dotfiles"

symbol() {
    [ $(git --git-dir=$HOME/$path/.git --work-tree=$HOME/$path status | grep -c "modified:\|deleted:") -gt 0 ] && echo "" || echo ""
    exit $?
}
class() {

    if git --git-dir=$HOME/$path/.git --work-tree=$HOME/$path status | grep -q "modified:"; then
        echo "git-mod"
    elif git --git-dir=$HOME/$path/.git --work-tree=$HOME/$path status | grep -q "deleted:"; then
        echo "git-del"
    else
        echo "alert-off"
    fi
}

[ "$1" = "icon" ]  && symbol && exit
[ "$1" = "class" ] && class  && exit