#!/bin/sh

symbol() {
    echo $(ip -4 addr show enp2s0f1 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
}

class() {
    [ $(xset q | grep 'LED mask' | sed 's/.*\([0-9]\)$/\1/') = 1 ] && echo "ip-box" && exit
    echo "ip-box"
}

[ "$1" = "ipadd" ] && symbol && exit
[ "$1" = "class" ] && class  && exit