#!/bin/sh
workspaces() {
ws2="2"
ws3="3"
ws4="4"
ws5="5"

# Unoccupied
un="0"

# check if Focused
f2=$(bspc query -D -d focused --names | grep "$ws2" )
f3=$(bspc query -D -d focused --names | grep "$ws3" )
f4=$(bspc query -D -d focused --names | grep "$ws4" )
f5=$(bspc query -D -d focused --names | grep "$ws5" )

# check if Occupied
o2=$(bspc query -D -d .occupied --names | grep "$ws2" )
o3=$(bspc query -D -d .occupied --names | grep "$ws3" )
o4=$(bspc query -D -d .occupied --names | grep "$ws4" )
o5=$(bspc query -D -d .occupied --names | grep "$ws5" )

# Icons

ic_2="󰖟" 
ic_3="󰨞"
ic_4=""
ic_5="󱔗"

ff2=""
ff3=""
ff4=""
ff5=""

if [ $f2 ]; then
    ic_2="󰖟"
    ff2="focused"
elif [ $f3 ]; then
    ic_3="󰨞"
    ff3="focused"
elif [ $f4 ]; then
    ic_4=""
    ff4="focused"
elif [ $f5 ]; then
    ic_5="󱔗"
    ff5="focused"
fi

echo 	"(box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" (button :onclick \"bspc desktop -f $ws2\"	:class \"$un$o2$f2 $ff2\"	 \"$ic_2\") (button :onclick \"bspc desktop -f $ws3\"	:class \"$un$o3$f3 $ff3\" \"$ic_3\") (button :onclick \"bspc desktop -f $ws4\"	:class \"$un$o4$f4 $ff4\"	\"$ic_4\") (button :onclick \"bspc desktop -f $ws5\"	:class \"$un$o5$f5 $ff5\" \"$ic_5\"))"

}
workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done
